# Generated by Django 2.0.3 on 2018-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=32, verbose_name='request id')),
                ('method', models.CharField(max_length=4, verbose_name='method')),
                ('headers', models.TextField(verbose_name='headers')),
                ('name', models.CharField(max_length=128, verbose_name='api name')),
                ('path', models.CharField(max_length=512, verbose_name='url')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='arguments')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='access time')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='http status')),
                ('code', models.CharField(max_length=10, verbose_name='api code')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('message', models.CharField(max_length=128, verbose_name='api message')),
                ('response', models.TextField(blank=True, null=True, verbose_name='api response')),
            ],
            options={
                'verbose_name_plural': '接口日志',
                'db_table': 'webapi_logs',
                'verbose_name': '接口日志',
            },
        ),
    ]
