# Generated by Django 2.0.3 on 2018-05-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='api_name',
            new_name='name',
        ),
    ]
