# Generated by Django 2.0.3 on 2018-05-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apirequest',
            table='api_request',
        ),
    ]
