# Generated by Django 2.0.3 on 2018-05-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0002_auto_20180511_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiRequest',
            new_name='ApiZenRequest',
        ),
        migrations.AlterModelTable(
            name='apizenrequest',
            table='apizen_request',
        ),
    ]
