# Generated by Django 2.0.3 on 2018-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0002_auto_20180503_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='success',
            field=models.BooleanField(default=False, verbose_name='success'),
        ),
    ]
