# Generated by Django 2.0.3 on 2018-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0003_auto_20180512_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apizenrequest',
            name='request_id',
            field=models.CharField(max_length=50, verbose_name='request id'),
        ),
    ]
