# Generated by Django 2.0.3 on 2018-05-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0004_auto_20180512_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='apizenrequest',
            name='querystring',
            field=models.TextField(blank=True, null=True, verbose_name='arguments'),
        ),
    ]
