# Generated by Django 2.0.3 on 2018-06-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apizen', '0005_apizenrequest_querystring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apizenrequest',
            name='message',
            field=models.CharField(max_length=512, verbose_name='api message'),
        ),
    ]
